### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by swim2see** [aefreedman/GameDevFall2017#1]
Chain animation keeps playing when grabber

Key doesn't always trigger on keyhole

Dial doesn't always trigger on turn 

Randomizer does not work properly -- uncommon, but scene repeat after one another.

Stove dial sprite doesn't turn properly.

Timer doesn't cap at .75s

The game lacks juice (don't know if that's considered a bug).

No sense of forward progression

**Comment by aefreedman** [comment]
6408cd838b0521c2695220f735d8b616bf2978ad
